apache/couchdb-fabric

src/fabric_view_all_docs.erl

remove compile warning

---

src/fabric_doc_update.erl

COUCHDB-2715
We would need this PR for COUCHDB-2635

Use couch_db:normalize_dbname

---

src/fabric_db_create.erl

This is one of the series of PRs to make couchdb plugable. I'll provide complete list of dependent PRs in https://github.com/apache/couchdb-couch repository.

Use `couch_db:validate_dbname/1`

---

src/fabric.erl

fabric:cleanup_index_files should check mrview/ directories

---

src/fabric_db_create.erl

Check if a DB exists prior to creating

---

src/fabric_db_create.erl

Don't create databases with toolong shard names

---

src/fabric_doc_open_revs.erl
src/fabric_doc_update.erl

Mock couch_log alongside couch_stats.

Fix eunit tests.

---

src/fabric_util.erl

Remove configurable replicator db name

---

include/fabric.hrl
src/fabric.erl
src/fabric_view.erl
src/fabric_view_map.erl
src/fabric_view_reduce.erl

Support raw view collation

---

include/fabric.hrl
src/fabric_view_map.erl

Honor update_seq=true for map view requests

---

src/fabric.erl

Improve spec to fix some dialyzer warnings.

Improve fabric:get_doc_count spec

---

src/fabric_doc_open_revs.erl

Filter out not_found replies when #doc{} is found
There are places in the codebase which assume  that the return from open_revs is always a list with one element in it. Fix the regression introduced in 9a1d0c54c78cef70d1a3992f3c71ef2878c498e4 by filtering out not_found replies when any of the returns contains `#doc{}`.
COUCHDB-67266

Filter out not_found replies when #doc{} is found

---

src/fabric_view_reduce.erl

Fix compilation warnings
COUCHDB-2730

Fix compilation warnings

---

src/fabric_db_update_listener.erl

A recent change that fixed the list comprehension ended up uncovering
the fact that we don't handle rexi_DOWN errors properly. This patch just
tracks the shards that are still listening and uses
`fabric_view:is_progress_possible/1` to know if we are still able to
continue listening for changes.
Fixes COUCHDB-3036

Fix fabric_db_update_listener rexi_DOWN handling

---

src/fabric.erl

Improve specs for:
- `fabric:update_docs`
- `fabric:all_docs`

Fix some specs

---

src/fabric_group_info.erl

It is possible to get a reply for same shard from different node sent before its collector get stopped in `remove_overlapping_shards`.
This running condition leads to a possibility of same info to be aggregated multiple times.
COUCHDB-3053

Ignore already received replies for same shards

---

src/fabric_doc_open_revs.erl

Current filter removing all `not_found`'s from the final reply in presence of any `{ok, Doc}` in it, which is not always the correct behaviour, since we can have missing doc for one of the passed revisions. In general, in absence of `latest` attribute, we are expecting one reply per revision which could be either #doc or not found.
This fix's making sure that we are removing `not_found`'s only for the revisions that also have `{ok, Doc}` reply.
COUCHDB-3097

Fix reply filter for open_revs

---

src/fabric.erl
src/fabric_rpc.erl

Implement clustered compaction functions

---

src/fabric_db_update_listener.erl
src/fabric_view_changes.erl

End continuous changes feeds cleanly if database is deleted

---

src/fabric_rpc.erl
src/fabric_view.erl
src/fabric_view_map.erl
src/fabric_view_reduce.erl

Trigger an update for all the shards. Will send a message to trigger
an update to shards that won't participate in the response due to not
being a ushard.
COUCHDB-3150

Update all shards with stale=update_after

---

src/fabric_rpc.erl

We managed to miss this change during the great merge as it was a
confusing mess in the cloudant/fabric repository. Its obvious in
hindsight once you see that we have a
`fabric_view_changes:handle_message/3` clause to handle the message.
COUCHDB-3178

Send a message when filtering a changes row

---

src/fabric_view.erl

Replace "stale" with "stable" when picking shards

---

src/fabric_rpc.erl

(This could be postponed until after 2.0 release. Issued to get comments and review).
When using selectors with `include_docs=true` can specify an optional fields
array in the POST request JSON body.
Each element in the array can be a json field (or even a key path
specified as field1.field2...). Resulting documents will contain only the
specified document fields.
For example:
```
http://.../d1/_changes?filter=_selector&include_docs=true
{
"selector": {"z" : {"$gte" : 1} }, "fields": ["field1", "field2"]
}
```
Will first select only document with "z" value >= 1, then will return only field1 and field2 in documents.
`{ "field1": "field1value", "field2": "field2value"}`
(This is a companion pr. Main pr is in couch repo)
Jira: COUCHDB-2988

Add optional `fields` to change feed selectors

---

src/fabric_rpc.erl
src/fabric_util.erl
src/fabric_view.erl

First phase for #mrargs{} record upgrade.

upgrade mrargs record phase 1

---

src/fabric_util.erl
src/fabric_view.erl

Second phase for #mrargs{} record upgrade.

77984 upgrade mrargs record phase2

---

src/fabric_doc_open_revs.erl

Currently, when one worker survives in fabric_open_revs, we return that
as the response. However, when all workers crash, we still return
{ok, []}. This changes the response to an error.
COUCHDB-3113

Return Error When Workers Crash

---

src/fabric_doc_open_revs.erl

We use {ok, []} in couch_db:open_doc_revs_int/3 as a return value
when the document does not exist and open_revs=all. This leads to an
incorrect all_workers_died error. We use ReplyCount and RealReplyCount
to distinguish between when no workers were actually used in a reply
versus when the document does not exist
COUCHDB-3113

Use RealReplyCount to distinguish worker replies and invalid docs
