apache/couchdb-fabric

src/fabric.erl
Since namespace support was added we can rely on it instead
COUCHDB-1145
=> Don't do manual filtering of _design docs

src/fabric_group_info.erl
We need to filter overlapping shards to prevent summarizing all sizes from all the shards, since we actually need the value from the one.
=> Fix incorrect size values for view index information

src/fabric_rpc.erl
This extends a change introduced in PR #37 to be used with filtered by view replication
Companion PR [apache/couchdb-couch#148](https://github.com/apache/couchdb-couch/pull/148)
=> Extend fetch ddoc logic for view filtered changes feeds

src/fabric_util.erl
Replace couch_db:normalize_dbname with couch_db:dbname_suffix since the
semantic of normalize_dbname has been changed. couch_db:normalize_dbname
would return all components of the path with shard info removed from it.
couch_db:dbname_suffix on the other hand would return the last component
of the path. It would also ensure that shard's suffix is removed from
the result.
This PR depends on https://github.com/apache/couchdb-couch/pull/160
COUCHDB-2983
=> Use couch_db:dbname_suffix in path_ends_with

src/fabric_db_update_listener.erl
`start_update_notifiers` returns list of `#workers{}`. 
However we expect `{Node, Reference}`.
=> start_update_notifiers returns list of #worker{}

src/fabric_rpc.erl
New option `create_if_missing` is added to couch_db:open.
Depends on https://github.com/apache/couchdb-couch/pull/174
=> Use create_if_missing option of couch_db:open_int

src/fabric.erl
fabric:get_all_security returns list of tuples `[{Worker, Reply}]`.
=> Fix return type in get_all_security

src/fabric_doc_open_revs.erl
When a user specified multiple revisions on a single branch to
fabric_doc_open_revs it would throw a function clause exception in
lists:zipwith/3. This was due to a bad assumption that there would only
ever be exactly one revision for every input revision.
Due to the possibility of having zero or more revisions for a given
revision when using latest=true this code had to be changed fairly
significantly.
COUCHDB-2863
=> Fix fabric_doc_open_revs

src/fabric_doc_open_revs.erl
fabric:update_docs is running in the context of a `read_repair` which is an
independent process started using `erlang:spawn/1`. This leads to a race
when we try to use `meck:history(fabric)`. Use of `meck:wait` ensures that
we call `meck:history` after `fabric:update_docs` has been called.
=> Use meck:wait to fix race condition

src/fabric_doc_open_revs.erl
In the cases when we receive rexi_DOWN or rexi_EXIT we call
handle_message with {ok, []}. This crashes lists:min/1. Since it expects
a list with at least one element.
COUCHDB-3037
=> Fix rexi_DOWN and rexi_EXIT handlers

src/fabric_doc_open_revs.erl
Message handler in `fabric_doc_open_revs` returns tagged with 'ok' list of the replies and not expected `{ok, Reply}` tuple. This makes reply to go through `Else` clause and skip `filter_reply` function.
=> Fix match in fabric_doc_open_revs reply

src/fabric_db_update_listener.erl
If a database is deleted and recreated the underlying shards have a
new name. Since we're watching the old names, we will never again see
an updated event. So, we stop this process if any watched shard is
deleted and it's someone elses job to recreate the listener for the
new shards.
COUCHDB-3054
=> End the listener if any shard is deleted

src/fabric.erl
Currently _view_cleanup endpoint is not cluster aware, only deletes
indexes on the node that gets the request. This will make it cluster
aware, deleting unused indexes on all nodes.
JIRA: COUCHDB-2779
=> make _view_cleanup endpoint cluster aware

src/fabric_doc_update.erl
change the error message so that it doesn't imply that all_or_nothing is a feature that will be implemented in the future.
=> clarify error when all_or_nothing attempted

src/fabric_db_update_listener.erl
Handle db deletion explicitly. Previously handle_db_event callback returned
`{stop, St}`. That return value was not handled by the caller, instead it
resulted in it being used as reason in an erlang:error, which then ended up in
the log.
Jira: COUCHDB-3149
=> Avoid throwing exception when deleting db in db updater listener

priv/stats_descriptions.cfg, src/fabric_rpc.erl
The open_shard RPC endpoint is used to grab security docs. There are
fairly aggressive timeouts on these requests so that when a node is too
busy it'll try the next shard. Rather than log everytime these fail
(which can be substantial under load) lets just use a counter that can
be graphed and alerted on.
COUCHDB-3234
=> Track open_shard timeouts with a counter

src/fabric_view_all_docs.erl
The Options array in fabric_view_all_docs contains the {user_ctx, _}
tuple but we omitted to pass it down to the open_doc command. This
caused several incorrect behaviours for the _users database which has
some special properties for privacy reasons.
COUCHDB-3232
=> Pass user_ctx down to fabric_rpc

src/fabric.erl
`fabric:design_docs/1` and `all_docs/5` can return `{error, Reason}`
see [here](https://github.com/apache/couchdb-fabric/blob/master/src/fabric_view_all_docs.erl#L46) and [here](https://github.com/apache/couchdb-fabric/blob/master/src/fabric.erl#L427)
=> Add `{error, Reason}` to typespecs

src/fabric_rpc.erl
Fixup for a previously merged commit bed5c67f9633d2837aa51c1aeb078fc671fa1e27
=> Use upgraded #mrargs{} instead of old one

src/fabric_view_all_docs.erl
When a keys array is passed to _all_docs, fabric translates this
to individual open_doc calls. The conflicts=true query parameter is
specified as a view-level option and is not, by default, parsed as
an option that should be passed to open_doc.
As a workaround, explicitly copy the view-level conflict parameter into
the document options before open_doc is called.
An alternative approach would be to address this when the query
parameters are parsed, setting conflicts=true in both #mrargs and
detail of fabric, I elected to make the change here instead.
Fixes #COUCHDB-3264
=> Include conflicts parameter in doc_options

src/fabric_rpc.erl, src/fabric_view_changes.erl
A view query that uses both a filter and a limit value can appear to
'hang' because the workers continue to run even after the number of
requested items have been returned, as workers that find no more
matches return 'no_pass' messages not 'change' messages, and thus the
short-circuiting code is never activated.
COUCHDB-3269
=> Handle no_pass message when limit is 0

src/fabric_group_info.erl
Group info on ddocs in _users database require admin privileges.
COUCHDB-3279
=> Add admin ctx on open ddoc in group_info

src/fabric_rpc.erl
Currently if an attachment was large enough or the connection was slow enough
such that it took more than fabric.request_timeout = 60000 milliseconds, the
fabric request would time out during attachment data transfer from coordinator
node to other nodes and the whole request would fail.
This was most evident when replicating database with large attachments.
The fix is to periodically send `attachment_chunk_received` to coordinator to
prevent the timeout.
COUCHDB-3302
=> Prevent attachment upload from timing out during update_docs fabric call
